from typing import List, Tuple, Type

from hypothesis import strategies as st
from hypothesis.strategies import SearchStrategy
from pydantic import ValidationError, BaseModel


def is_integer(s: str) -> bool:
    """
    Return true if s represents an integer, and false otherwise.

    :param s: value to check if represents an integer
    :return: true if s represents an integer, false otherwise
    >>> is_integer("5")
    True
    >>> is_integer("five")
    False
    >>> is_integer("-5")
    True
    >>> is_integer("5.1")
    False
    """
    try:
        int(s)
    except ValueError:
        return False
    else:
        return True


INVALID_INTS = st.one_of(
    st.integers().map(lambda x: x + 0.1), st.text().filter(lambda s: not is_integer(s))
)


def valid_invalid_from_allowed(
    allowed: List[str],
) -> Tuple[SearchStrategy, SearchStrategy]:
    """
    Construct valid and invalid search strategies from a given list of allowed values.

    :param allowed: values which are allowed
    :return: valid and invalid strategies, where valid strategies are those from allowed, and
        the text generated by the two strategies is disjoint
    """
    valid = st.sampled_from(allowed)
    invalid = st.text().filter(lambda s: s not in allowed)
    return valid, invalid


def success_from_kw(type_: Type[BaseModel], **kwargs) -> None:
    """
    Construct an instance of `type_` via provided keyword arguments, and expect both that
    construction is successful and all fields match their expected values in kwargs.

    :param type_: the type to construct
    :param kwargs: keyword arguments to type_ constructor
    """
    event = type_.parse_obj(kwargs)
    for name, val in kwargs.items():
        assert val == getattr(event, name)


def xfail_from_kw(type_: Type[BaseModel], **kwargs) -> None:
    """
    Construct an instance of `type_` via provided keyword arguments, and expect that
    construction fails, raising a ValidationError.

    :param type_: the type to construct
    :param kwargs: keyword arguments to type_ constructor
    """
    try:
        type_.parse_obj(kwargs)
    except ValidationError:
        return
    else:
        assert False, f"Expected construction of {type_.__name__} with {kwargs} to fail"
